// This file was autogenerated by porter, an SFU CMPT 886 project
// the template used was in ca/sfu/cs/porter/driver.stg
// https://theantlrguy.atlassian.net/wiki/display/ST/Five+minute+Introduction

package 

//TODO imports?

class Driver {

    @FunctionalInterface
    interface Test{
        void runTest() throws Throwable;
    }

    public static void main(String[] args){

 instance = new ();

        runTest(instance::test001);
    }

    private static void runTest(Test test){
        try{
            test.runTest();
        }
        catch (Throwable throwable) {
            throwable.printStackTrace();
        }
    }
}


