// This file was autogenerated by porter, an SFU CMPT 886 project
// the template used was in ca/sfu/cs/porter/driver.stg
// https://theantlrguy.atlassian.net/wiki/display/ST/Five+minute+Introduction

package ca.sfu.cs.porter;

//TODO imports?

class RegressionTest0Driver {

    public static void main(String[] args){

        RegressionTest0 instance = new RegressionTest0();

        try{
            instance.test001();
        }
        catch (Throwable throwable) {
            throwable.printStackTrace();
        }
    }
}


