// This file was autogenerated by porter, an SFU CMPT 886 project
// the template used was in ca/sfu/cs/porter/driver.stg
// https://theantlrguy.atlassian.net/wiki/display/ST/Five+minute+Introduction


//TODO imports?

class RegressionTest0NoPackageDriver {

    public static void main(String[] args){

        RegressionTest0NoPackage instance = new RegressionTest0NoPackage();

        try{
            instance.test001();
        }
        catch (Throwable throwable) {
            throwable.printStackTrace();
        }
    }
}


